### ISSUE TITLE
Mingus can't start after updated to emacs 28

### ISSUE THREAD

**Issue by xiangsheng** [pft/mingus#39] opened 2022-05-03 15:04 UTC
After updating to emacs 28 recently, I find mingus can't start any more and get the following error.

```
error in process filter: Symbol's function definition is void: _mpdgl
```

Especially annoying thing is that the emacs got stuck and can't respond to `C-g` even.

**Comment by seagle0128** [comment] 2022-05-05 10:10
I can confirm it does work well on 28. Try reinstalling the package.

**Comment by xiangsheng** [comment] 2022-05-05 12:30
If you reinstall this package and open it immediately, yes, it works.
But if you restart emacs and open mingus again, it got stuck again.
It seems that a library, ie libmpdee.el, mingus uses is outdated.
Some macros in this library can't be evaluated automatically at startup.
Someone gives me a modified libmpdee.el, with which the bug is fixed.
See this link: https://pastebin.com/w0n2HXWU.
It seems that we only need to add some # before some lambda functions.

Best wishes, xs


On 2022.05.05 03:11, Vincent Zhang wrote:
>I can confirm it does work well on 28. Try reinstalling the package.
>
>—
>Reply to this email directly, view it on GitHub, or unsubscribe.
>You are receiving this because you authored the thread.*Message ID: <pft/mingus
***@***.***>
>

**Comment by stardiviner** [comment] 2022-06-12 07:07
I got same problem. Even I delete mingus and libmpdee both, and reinstall again, and restart Emacs still got same problem.

**Comment by pft** [comment] 2022-07-04 06:58
> If you reinstall this package and open it immediately, yes, it works. But if you restart emacs and open mingus again, it got stuck again. It seems that a library, ie libmpdee.el, mingus uses is outdated. Some macros in this library can't be evaluated automatically at startup. Someone gives me a modified libmpdee.el, with which the bug is fixed. See this link: https://pastebin.com/w0n2HXWU. It seems that we only need to add some # before some lambda functions. 

Finally got around to looking at this, now the pastebin is gone. Care to reshare @xiangsheng ?

**Comment by xiangsheng** [comment] 2022-07-04 07:12
https://pastebin.com/a5grGz1Z @pft

**Comment by seagle0128** [comment] 2022-07-04 08:32
@pft I tested with https://pastebin.com/a5grGz1Z, and it's working well. Can you please integrate it instead of the deprecated `libmpdee` package? Or upgrade `libmpdee` package?

**Comment by xiangsheng** [comment] 2022-07-04 09:02
I think it may be better to integrate `libmpdee` into mingus, since no one seems to maintain `libmpdee` any more.

**Comment by andyetitmoves** [comment] 2022-08-21 15:56
I have just merged a PR which someone else raised a while on a similar issue, please try the latest version and let me know..

**Comment by seagle0128** [comment] 2022-08-21 16:38
@andyetitmoves May I know where can I get the PR?

**Comment by pft** [comment] 2022-08-21 16:43
> I have just merged a PR which someone else raised a while on a similar issue, please try the latest version and let me know..

Awesome. Integrating libmpdee was something I wasn't keen on doing. This indeed should fix it, since it's functionally equivalent to the shared patch.

@seagle0128 it's a PR for libmpdee.

**Comment by pft** [comment] 2022-08-25 08:42
Note: when installing from melpa, I had to remove the cached version in order to update to the new libmpdee.

**Closed by pft** 2022-08-25 08:42 UTC

**Comment by pft** [comment] 2022-08-25 09:38
Hmm, on that cached thing: mingus has 

```lisp
;; Package-Requires: ((libmpdee "2.1"))
```
I think it'd be better if @andyetitmoves updated the version number of libmpdee and mingus updated the Package-Requires line.

**Comment by pft** [comment] 2022-08-25 09:42
Created in issue for that: https://github.com/andyetitmoves/libmpdee/issues/9

**Comment by andyetitmoves** [comment] 2022-08-25 09:58
Now bumped up to 2.2.

**Comment by pft** [comment] 2022-08-25 10:30
Thanks, I also bumped the dependency now.

**Comment by xiangsheng** [comment] 2022-08-25 13:20
It is quite pleasant to see people are maintaining the old packages. That makes emacs a lovely place to play around. Thanks, @pft and @andyetitmoves .
