### ISSUE TITLE
mingus not working on Emacs28

### ISSUE THREAD

**Issue by OrionRandD** [pft/mingus#40] opened 2022-08-21 02:43 UTC
error in process filter: funcall: Symbol’s function definition is void: _mpdgl
error in process filter: Symbol’s function definition is void: _mpdgl
funcall: Symbol’s function definition is void: _mpdgl

**Comment by pft** [comment] 2022-08-25 08:32
This is a duplicate of https://github.com/pft/mingus/issues/39

**Closed by pft** 2022-08-25 08:32 UTC
